name: steels
description: A New Woocommerce Template
version: 1.0.3+3

environment:
  sdk: '>=2.19.1 <3.0.6'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  http: ^0.13.6
  shared_preferences: ^2.1.1
  get: ^4.6.5
  fluttertoast: ^8.2.1
  dependencies:
  flutter_image_slideshow: ^0.1.5
  readmore: ^2.1.0
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0
  cached_network_image: ^3.2.3
  ionicons: ^0.2.2
  flutter_html_v3: ^3.0.6
  shimmer: ^3.0.0
  razorpay_flutter: ^1.3.5
  intl: ^0.18.0
  flutter_rating_bar: ^4.0.1
  firebase_remote_config: ^4.2.3
  package_info_plus: ^4.0.2
  url_launcher: ^6.1.11
  firebase_core: ^2.12.0
  cloud_firestore: ^4.8.1
  image_picker: ^0.8.7+5
  image_cropper: ^4.0.1
  flutter_svg: ^2.0.5
  firebase_messaging: ^14.6.3
  flutter_local_notifications: ^14.1.1
  audioplayers: ^4.1.0
  flutter_automation: ^2.0.0







dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/onboarding/
    - assets/flags/
    - assets/audio/



  fonts:
    - family: 'bold'
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: 'semi-bold'
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
    - family: 'medium'
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: 'regular'
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
